// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support //\t@contact.url\thttp://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/testapi": {
            "get": {
                "description": "get string",
                "produces": [
                    "text/plain"
                ],
                "summary": "outputs test message",
                "operationId": "crop",
                "responses": {
                    "200": {
                        "description": "./myfile.txt",
                        "schema": {
                            "type": "file"
                        },
                        "headers": {
                            "SuperMeta": {
                                "type": "string",
                                "description": "i am super meta data"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8573",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Swagger Example API",
	Description:      "This is a sample server for company.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
