basePath: /
host: localhost:8573
info:
  contact:
    email: support@swagger.io
    name: "API Support //\t@contact.url\thttp://www.swagger.io/support"
  description: This is a sample server for company.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "2.0"
paths:
  /testapi/:
    get:
      description: getting file
      operationId: crop
      produces:
      - image/png
      responses:
        "200":
          description: hello world
          headers:
            SuperMeta:
              description: i am super meta data
              type: string
          schema:
            type: string
      summary: returns file
schemes:
- http
swagger: "2.0"
